name: CI

# Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: |
          cd app
          yarn
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: app/dist # The folder the action should deploy from.
